/**
 * Query Builder - Seed dictionaries per locale for cold start
 * NO medical terms, only common pet shopping queries
 */

const SEED_DICTIONARIES: Record<string, string[]> = {
  'pt-BR': [
    'ração cachorro',
    'ração gato',
    'petiscos',
    'coleira',
    'areia higiênica',
    'brinquedo',
    'cama pet',
    'comedouro',
    'bebedouro',
    'vermífugo',
    'antipulgas',
    'shampoo pet',
    'tapete higiênico',
    'guia',
    'focinheira',
    'osso',
    'arranhador',
    'casinha',
    'gaiola',
    'aquário',
  ],
  'en': [
    'dog food',
    'cat food',
    'pet treats',
    'leash',
    'cat litter',
    'pet toy',
    'pet bed',
    'food bowl',
    'water bowl',
    'flea treatment',
    'pet shampoo',
    'training pads',
    'collar',
    'muzzle',
    'chew toy',
    'scratching post',
    'pet house',
    'cage',
    'aquarium',
    'pet carrier',
  ],
  'es': [
    'comida perro',
    'comida gato',
    'golosinas',
    'correa',
    'arena gatos',
    'juguete',
    'cama mascota',
    'comedero',
    'bebedero',
    'collar',
    'antipulgas',
    'champú mascota',
    'pañales perro',
    'bozal',
    'hueso',
    'rascador',
    'caseta',
    'jaula',
    'acuario',
    'transportin',
  ],
  'fr': [
    'croquettes chien',
    'croquettes chat',
    'friandises',
    'laisse',
    'litière chat',
    'jouet',
    'panier',
    'gamelle',
    'abreuvoir',
    'collier',
    'antipuces',
    'shampoing',
    'tapis propreté',
    'muselière',
    'os à mâcher',
    'griffoir',
    'niche',
    'cage',
    'aquarium',
    'sac transport',
  ],
  'it': [
    'cibo cani',
    'cibo gatti',
    'snack',
    'guinzaglio',
    'lettiera gatti',
    'giocattolo',
    'cuccia',
    'ciotola cibo',
    'ciotola acqua',
    'collare',
    'antipulci',
    'shampoo',
    'tappetini',
    'museruola',
    'osso',
    'tiragraffi',
    'casetta',
    'gabbia',
    'acquario',
    'trasportino',
  ],
};

export function seedDictionary(locale: string): string[] {
  return SEED_DICTIONARIES[locale] || SEED_DICTIONARIES['en'];
}
